(function(){
'use strict';
const KEY='tilosStaffWorkspace:v1',DB_NAME='tilosStaffMedia',MEDIA_STORE='media',clone=v=>JSON.parse(JSON.stringify(v));
const baseState=()=>({version:3,profile:{name:'',providerName:'',email:'',signatureName:''},learners:[],reviews:[],observations:[],selectedLearnerId:'',updatedAt:new Date().toISOString()});
function normalizeLearner(l={}){const base={courseId:'ST0095',courseName:'Bricklayer',courseVersion:'v1.2',courseOption:'',qualificationType:'Apprenticeship',nvqOptionalUnitIds:[]},snap=window.TilosCourses?.snapshot?.({...base,...l})||base;return{...base,...l,...snap,nvqOptionalUnitIds:[...(l.nvqOptionalUnitIds||snap.nvqOptionalUnitIds||[])]}}
function normalizeObservation(o={}){return{...o,selectedKSBs:Array.isArray(o.selectedKSBs)?o.selectedKSBs:[],automaticKSBs:Array.isArray(o.automaticKSBs)?o.automaticKSBs:[],nvqPrimaryCriteria:Array.isArray(o.nvqPrimaryCriteria)?o.nvqPrimaryCriteria:[],nvqDirectCriteria:Array.isArray(o.nvqDirectCriteria)?o.nvqDirectCriteria:[],nvqAutomaticMappings:Array.isArray(o.nvqAutomaticMappings)?o.nvqAutomaticMappings:[],nvqSuggestedMappings:Array.isArray(o.nvqSuggestedMappings)?o.nvqSuggestedMappings:[],media:Array.isArray(o.media)?o.media:[],discussionRecordings:Array.isArray(o.discussionRecordings)?o.discussionRecordings:[]}}
function read(){try{const raw=localStorage.getItem(KEY);if(!raw)return baseState();const p=JSON.parse(raw);return{...baseState(),...p,profile:{...baseState().profile,...(p.profile||{})},learners:(Array.isArray(p.learners)?p.learners:[]).map(normalizeLearner),reviews:Array.isArray(p.reviews)?p.reviews:[],observations:(Array.isArray(p.observations)?p.observations:[]).map(normalizeObservation)}}catch(_){return baseState()}}
function write(s){s.version=3;s.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(s));return s}
function mutate(fn){const s=read();fn(s);return write(s)}
function numericSuffix(id){return Number(String(id||'').replace(/\D/g,''))||0}
function nextId(prefix,rows){return `${prefix}${String(Math.max(0,...rows.map(x=>numericSuffix(x.id)))+1).padStart(4,'0')}`}
const today=()=>new Date().toISOString().slice(0,10);
function addMonths(date,months){if(!date)return'';const d=new Date(`${date}T12:00:00`);if(Number.isNaN(d.getTime()))return'';d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)}
function learnerTemplate(data={}){const snap=window.TilosCourses?.snapshot?.(data)||{};return normalizeLearner({id:data.id||`L${crypto.randomUUID().slice(0,8).toUpperCase()}`,name:data.name||'',employer:data.employer||'',startDate:data.startDate||'',plannedEndDate:data.plannedEndDate||'',apprenticeNumber:data.apprenticeNumber||'',...snap,courseId:data.courseId||snap.courseId||'ST0095',nvqOptionalUnitIds:[...(data.nvqOptionalUnitIds||[])],status:data.status||'Active',createdAt:data.createdAt||new Date().toISOString()})}
const qualification=l=>window.TilosCourses?.longLabel?.(l?.courseId)||l?.courseName||'Bricklayer · ST0095';
function reviewTemplate(l,p,existing=[]){const previous=existing.filter(r=>r.learnerId===l.id&&r.status==='Completed').sort((a,b)=>String(b.reviewDate).localeCompare(String(a.reviewDate)))[0];return{id:nextId('REV',existing),learnerId:l.id,courseSnapshot:window.TilosCourses?.snapshot?.(l)||{},reviewType:'Professional Review',reviewDate:today(),previousReviewDate:previous?.reviewDate||'',nextReviewDate:addMonths(today(),3),identitySnapshot:{learnerName:l.name,qualification:qualification(l),employer:l.employer||'',assessor:p.name||'',provider:p.providerName||''},apprenticeProgress:{previous:clone(previous?.apprenticeProgress?.current||{}),current:{}},progress:{achievements:'',newLearning:'',development:''},apprentice:{comments:'',concern:'No concerns',concernNotes:''},employer:{rating:'On track',comments:'',representativeName:'',representativeRole:''},assessor:{judgement:'On track',comments:''},otj:{status:'',planned:'Yes',relevant:'Yes',comments:'',concernNotes:''},englishMaths:{english:'Not required / already achieved',englishNotes:'',maths:'Not required / already achieved',mathsNotes:''},mandatoryQualification:{status:'Not applicable',notes:''},wellbeing:{support:'No',safeguarding:'No',notes:''},readiness:{status:'Not yet ready',notes:''},targets:[],trainingPlan:{change:'No',notes:''},signatures:{apprenticeName:l.name,apprenticeSigned:false,employerName:'',employerRole:'',employerSigned:false,assessorName:p.signatureName||p.name||'',assessorSigned:false},status:'Draft',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function observationTemplate(l,p,existing=[]){return normalizeObservation({id:nextId('OBS',existing),learnerId:l.id,courseSnapshot:window.TilosCourses?.snapshot?.(l)||{},date:today(),areaId:'',area:'',activityId:'',activity:'',location:'',assessor:p.name||'',selectedKSBs:[],automaticKSBs:[],nvqPrimaryCriteria:[],nvqDirectCriteria:[],nvqAutomaticMappings:[],nvqSuggestedMappings:[],notes:'',hasDiscussion:false,discussionNotes:'',media:[],discussionRecordings:[],outcome:'Evidence collected',feedback:'',signatureName:p.signatureName||p.name||'',signed:false,status:'Draft',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}
function openMedia(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(MEDIA_STORE))db.createObjectStore(MEDIA_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function mediaTx(mode,work){const db=await openMedia();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,mode),store=tx.objectStore(MEDIA_STORE);let req;try{req=work(store)}catch(e){db.close();reject(e);return}req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error)})}
const MediaStore={async save(file){const id=`M${crypto.randomUUID()}`;await mediaTx('readwrite',s=>s.put({id,name:file.name||'evidence-file',type:file.type||'application/octet-stream',size:file.size||0,createdAt:new Date().toISOString(),blob:file}));return{id,name:file.name||'evidence-file',type:file.type||'application/octet-stream',size:file.size||0}},get:id=>mediaTx('readonly',s=>s.get(id)),all:()=>mediaTx('readonly',s=>s.getAll()),remove:id=>mediaTx('readwrite',s=>s.delete(id))};
window.TilosStaffStore={read,write,mutate,today,addMonths,profile:()=>read().profile,saveProfile:p=>mutate(s=>{s.profile={...s.profile,...p}}),learners:()=>read().learners.filter(l=>l.status!=='Deleted'),learner:id=>read().learners.find(l=>l.id===id),
saveLearner(data){let saved;mutate(s=>{const i=s.learners.findIndex(l=>l.id===data.id),merged=i>=0?{...s.learners[i],...data}:data;saved=learnerTemplate(merged);if(i>=0)s.learners[i]=saved;else s.learners.push(saved);s.selectedLearnerId=saved.id});return saved},
archiveLearner:id=>mutate(s=>{const l=s.learners.find(x=>x.id===id);if(l)l.status='Withdrawn'}),reinstateLearner:id=>mutate(s=>{const l=s.learners.find(x=>x.id===id);if(l)l.status='Active'}),selectedLearnerId:()=>read().selectedLearnerId,selectLearner:id=>mutate(s=>{s.selectedLearnerId=id||''}),
reviews:id=>read().reviews.filter(r=>!id||r.learnerId===id).sort((a,b)=>String(b.reviewDate).localeCompare(String(a.reviewDate))),review:id=>read().reviews.find(r=>r.id===id),newReview:l=>reviewTemplate(l,read().profile,read().reviews),saveReview(r){r.updatedAt=new Date().toISOString();mutate(s=>{const i=s.reviews.findIndex(x=>x.id===r.id);if(i>=0)s.reviews[i]=clone(r);else s.reviews.push(clone(r))});return r},deleteReview:id=>mutate(s=>{s.reviews=s.reviews.filter(r=>r.id!==id)}),
observations:id=>read().observations.filter(o=>!id||o.learnerId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date))),observation:id=>{const o=read().observations.find(x=>x.id===id);return o?normalizeObservation(o):undefined},newObservation:l=>observationTemplate(l,read().profile,read().observations),saveObservation(o){o=normalizeObservation(o);o.updatedAt=new Date().toISOString();mutate(s=>{const i=s.observations.findIndex(x=>x.id===o.id);if(i>=0)s.observations[i]=clone(o);else s.observations.push(clone(o))});return o},async deleteObservation(id){const o=normalizeObservation(read().observations.find(x=>x.id===id)||{});for(const m of[...(o.media||[]),...(o.discussionRecordings||[])])await MediaStore.remove(m.id).catch(()=>{});return mutate(s=>{s.observations=s.observations.filter(x=>x.id!==id)})},MediaStore,exportData:()=>clone(read()),importData(d){if(!d||typeof d!=='object')throw new Error('Invalid Andros backup');return write({...baseState(),...d,version:3})}};
}());
