(function(){
'use strict';
const registry=window.EviaCourseRegistry||{all:window.EVIA_COURSES||{},meta:window.EVIA_COURSE_META||{}};
const NVQ_IDS=new Set(['NVQ6570-L2','NVQ6570-L3']);
const TOP=[
 {id:'ST0095',label:'Bricklayer',detail:'ST0095 v1.2'},
 {id:'ST0264',label:'Carpentry & Joinery',detail:'ST0264 v1.4',pathways:[{id:'ST0264-SITE',label:'Site Carpenter'},{id:'ST0264-JOINER',label:'Architectural Joiner'}]},
 {id:'NVQ6570-L2',label:'Level 2 NVQ Trowel Occupations',detail:'City & Guilds 6570-04'},
 {id:'NVQ6570-L3',label:'Level 3 NVQ Trowel Occupations',detail:'City & Guilds 6570-05'},
 {id:'ST0171',label:'Property Maintenance Operative',detail:'ST0171 v1.1'}
];
function canonicalId(value){const s=String(value||'').trim();if(!s)return'';const u=s.toUpperCase();if(NVQ_IDS.has(u))return u;if(/6570[-_ ]?0?4|6570.*L2|L2.*6570|NVQ.*L2|LEVEL\s*2.*TROWEL/i.test(s))return'NVQ6570-L2';if(/6570[-_ ]?0?5|6570.*L3|L3.*6570|NVQ.*L3|LEVEL\s*3.*TROWEL/i.test(s))return'NVQ6570-L3';if(/ST0264.*SITE|SITE.*CARP/i.test(s))return'ST0264-SITE';if(/ST0264.*JOIN|ARCHITECTURAL.*JOIN/i.test(s))return'ST0264-JOINER';if(/ST0264/i.test(s))return'ST0264';if(/ST0171/i.test(s))return'ST0171';if(/ST0095/i.test(s)||/^BRICKLAYER$/i.test(s))return'ST0095';return s}
function resolveCourseId(l){if(typeof l==='string')return canonicalId(l);l=l||{};const descriptive=`${l.courseName||''} ${l.courseOption||''} ${l.qualificationType||''} ${l.courseSnapshot?.courseName||''} ${l.courseSnapshot?.qualificationType||''} ${l.courseSnapshot?.courseId||''}`;const fromDescription=canonicalId(descriptive);if(NVQ_IDS.has(fromDescription)||/^ST0264-(SITE|JOINER)$/.test(fromDescription))return fromDescription;return canonicalId(l.courseId||l.courseSnapshot?.courseId||fromDescription||'ST0095')||'ST0095'}
const get=id=>{const c=canonicalId(id);return registry.all?.[c]||window.EVIA_COURSES?.[c]||registry.all?.[id]||window.EVIA_COURSES?.[id]||null};
const meta=id=>{const c=canonicalId(id);return registry.meta?.[c]||window.EVIA_COURSE_META?.[c]||registry.meta?.[id]||window.EVIA_COURSE_META?.[id]||{}};
const isNVQ=id=>{const c=typeof id==='object'?resolveCourseId(id):canonicalId(id);if(NVQ_IDS.has(c))return true;const m=meta(c),d=get(c);return String(m.qualificationType||d?.qualificationType||'').toUpperCase()==='NVQ'};
const profileFor=l=>({courseId:resolveCourseId(l),nvqOptionalUnitIds:[...(l?.nvqOptionalUnitIds||l?.courseSnapshot?.nvqOptionalUnitIds||[])]});
const slug=v=>String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const normalizeAreas=source=>Object.fromEntries(Object.entries(source||{}).map(([areaId,a])=>[areaId,{...a,activities:(a.activities||[]).map((x,i)=>({...x,id:x.id||slug(x.label||x.title)||`${areaId}-${i+1}`}))}]));
function label(id){const c=typeof id==='object'?resolveCourseId(id):canonicalId(id),d=get(c),m=meta(c);return d?.shortName||m.shortName||d?.name||m.name||TOP.flatMap(x=>x.pathways?.length?x.pathways:[x]).find(x=>x.id===c)?.label||c||'Course'}
function longLabel(id){const c=typeof id==='object'?resolveCourseId(id):canonicalId(id),d=get(c),m=meta(c),top=TOP.find(x=>x.id===c),path=TOP.flatMap(x=>x.pathways||[]).find(x=>x.id===c);if(c==='NVQ6570-L2')return'Level 2 NVQ Trowel Occupations · City & Guilds 6570-04';if(c==='NVQ6570-L3')return'Level 3 NVQ Trowel Occupations · City & Guilds 6570-05';if(path)return`${path.label} · ST0264 v1.4`;if(top?.detail)return`${top.label} · ${top.detail}`;const name=d?.name||m.name||label(c),std=m.standard||d?.qualificationNumber||c,ver=m.version?` · ${m.version}`:'';return `${name}${std?` · ${std}`:''}${ver}`}
function optionalUnits(id){const c=typeof id==='object'?resolveCourseId(id):canonicalId(id);if(!isNVQ(c)||!window.NVQ_TROWEL?.dataForCourse)return[];const d=NVQ_TROWEL.dataForCourse(c);return(d?.optionalUnits||[]).map(x=>({id:String(x.id),title:x.title||`Unit ${x.id}`,glh:x.glh}))}
function areas(l){const p=profileFor(l);if(isNVQ(p.courseId)&&window.NVQ_TROWEL?.areas)return normalizeAreas(NVQ_TROWEL.areas(p)||{});return normalizeAreas(window.EVIA_MAPPING?.forCourse?.(p.courseId)||{})}
function activity(areaId,activityId,l){return areas(l)?.[areaId]?.activities?.find(x=>String(x.id)===String(activityId))||null}
function apprenticeshipItems(l){const c=get(resolveCourseId(l))||{knowledge:{},skills:{},behaviours:{}};return[...Object.entries(c.skills||{}).map(([code,text])=>({code,text,type:'Skill'})),...Object.entries(c.knowledge||{}).map(([code,text])=>({code,text,type:'Knowledge'})),...Object.entries(c.behaviours||{}).map(([code,text])=>({code,text,type:'Behaviour'}))]}
function holisticKSBs(l,direct=[]){const c=get(resolveCourseId(l))||{},sel=new Set(direct),auto=new Set();for(const code of sel){const paired=c.pairs?.[code];(Array.isArray(paired)?paired:(paired?[paired]:[])).forEach(x=>{if(x&&!sel.has(x))auto.add(x)})}return{direct:[...sel],automatic:[...auto]}}
function nvqMap(l,act,discussion=false){const p=profileFor(l),data=window.NVQ_TROWEL?.dataForCourse?.(p.courseId);if(!isNVQ(p.courseId)||!data)return null;const practical=[...(act?.nvqPracticalCriteria||[])],knowledge=discussion?[...(act?.nvqKnowledgeCriteria||[])]:[],direct=[...new Set([...practical,...knowledge])],automatic=[],suggested=[];for(const source of direct){const links=data.mappingGraph?.[source]||{};(links.automatic||[]).forEach(x=>automatic.push({source,target:x.target,score:x.score}));(links.confirm||[]).forEach(x=>suggested.push({source,target:x.target,score:x.score}))}const uniqRows=rows=>{const seen=new Set();return rows.filter(x=>{const k=`${x.source}>${x.target}`;if(seen.has(k))return false;seen.add(k);return true})};return{nvqPrimaryCriteria:[...(act?.nvqPrimaryCriteria||[])],nvqDirectCriteria:direct,nvqAutomaticMappings:uniqRows(automatic),nvqSuggestedMappings:uniqRows(suggested)}}
function criterionLabel(k,l){const id=typeof l==='object'?resolveCourseId(l):canonicalId(l||''),data=id?window.NVQ_TROWEL?.dataForCourse?.(id):null,item=data?.criteria?.find?.(x=>x.key===k);return item?`${item.unitId} AC ${item.acId}`:(window.NVQ_TROWEL?.criterionLabel?.(k)||k)}
function coverage(l,records=[]){const p=profileFor(l),complete=(records||[]).filter(o=>o&&o.status==='Completed');if(isNVQ(p.courseId)&&window.NVQ_TROWEL?.coverage){const c=NVQ_TROWEL.coverage(complete,p);return{percent:c?.percent||0,count:c?.count??c?.covered?.length??0,total:c?.total??c?.requirements?.length??0,label:'AC coverage'}}const items=apprenticeshipItems(l),codes=new Set();complete.forEach(o=>{(o.selectedKSBs||[]).forEach(x=>codes.add(x));(o.automaticKSBs||[]).forEach(x=>codes.add(x))});return{percent:items.length?Math.round(codes.size/items.length*100):0,count:codes.size,total:items.length,label:'KSB coverage'}}
function snapshot(l){const id=resolveCourseId(l),m=meta(id),c=get(id);return{courseId:id,courseName:c?.name||m.name||label(id),courseVersion:m.version||'',courseOption:m.option||'',qualificationType:isNVQ(id)?'NVQ':(m.qualificationType||'Apprenticeship'),nvqOptionalUnitIds:[...(l?.nvqOptionalUnitIds||l?.courseSnapshot?.nvqOptionalUnitIds||[])]}}
window.TilosCourses={TOP,canonicalId,resolveCourseId,get,meta,label,longLabel,isNVQ,optionalUnits,areas,activity,apprenticeshipItems,holisticKSBs,nvqMap,criterionLabel,coverage,snapshot,profileFor};
}());